import { chromium } from "playwright-core";
import { resolve } from "node:path";
import { tmpdir } from "node:os";

const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true, args: ["--no-sandbox", "--use-fake-device-for-media-stream"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 1050 }, acceptDownloads: true });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
try {
  await page.goto(process.env.EDITOR_URL || process.env.RESTYLE_EDITOR_URL || "http://127.0.0.1:5173/", { waitUntil: "networkidle" });
  await page.getByRole("button", { name: "Record" }).waitFor();
  if (await page.locator(".modeRow").count()) throw new Error("Timed recording modes are still visible");
  if (await page.getByRole("button", { name: /Filters?|Effects/ }).count()) throw new Error("A filter control is still visible");
  const cameraRatio = page.getByRole("button", { name: "Ratio", exact: true });
  if (!(await cameraRatio.innerText()).includes("9:16")) throw new Error("Camera ratio control should show the default ratio");
  await cameraRatio.click();
  const triggerBox = await cameraRatio.boundingBox();
  const menuBox = await page.getByRole("menu", { name: "Aspect ratio" }).boundingBox();
  if (!triggerBox || !menuBox || menuBox.y < triggerBox.y + triggerBox.height - 2) throw new Error("Camera ratio menu should open below its control");
  await page.screenshot({ path: resolve(tmpdir(), "capture-ratio-menu.png") });
  if (!(await page.getByRole("menuitemradio").first().innerText()).includes("9:16")) throw new Error("Selected ratio should be first in the menu");
  if (await page.getByRole("menuitemradio", { name: "9:16" }).getAttribute("data-on") !== "true") throw new Error("9:16 should be the default ratio");
  if (await page.getByRole("menuitemradio", { name: "Original" }).count()) throw new Error("Original should not appear as a ratio option");
  await page.getByRole("menuitemradio", { name: "1:1" }).click();
  if (!(await cameraRatio.innerText()).includes("1:1")) throw new Error("Camera ratio control did not update after selection");
  await cameraRatio.click();
  if (!(await page.getByRole("menuitemradio").first().innerText()).includes("1:1")) throw new Error("Newly selected ratio should be first in the menu");
  await page.getByRole("menuitemradio", { name: "9:16" }).click();
  await cameraRatio.click();
  await page.keyboard.press("Escape");
  if (await page.getByRole("menuitemradio", { name: "9:16" }).count()) throw new Error("Ratio menu should close on Escape");
  await page.screenshot({ path: resolve(tmpdir(), "capture-camera.png") });
  await page.getByRole("button", { name: "Record" }).click();
  await page.waitForFunction(() => Number(document.querySelector('.shutter circle[data-seconds]')?.getAttribute('data-seconds')) > .1);
  const early = Number(await page.locator('.shutter circle[data-seconds]').getAttribute('data-seconds'));
  await page.waitForTimeout(1400);
  const later = Number(await page.locator('.shutter circle[data-seconds]').getAttribute('data-seconds'));
  if (later <= early || await page.locator('.shutter').getAttribute('data-scale') !== '10') throw new Error('Live ring does not animate on a 10-second scale');
  await page.getByRole("button", { name: "Stop recording" }).click();
  await page.getByRole("button", { name: "Open editor" }).waitFor();
  const shortArc = Number((await page.locator('.shutter svg circle').getAttribute('stroke-dasharray'))?.split(' ')[0]);
  if (shortArc >= 2 * Math.PI * 41 * .25) throw new Error('Short take incorrectly fills the ring');
  await page.getByRole("button", { name: "Open editor" }).click();
  await page.getByRole("heading", { name: "Edit" }).waitFor();
  await page.screenshot({ path: resolve(tmpdir(), "capture-editor.png") });
  await page.locator(".tlClip").click();
  await page.getByRole("button", { name: "Collapse clip tools" }).waitFor();
  await page.getByRole("button", { name: "Collapse clip tools" }).click();
  await page.getByRole("button", { name: "Text", exact: true }).click();
  await page.getByRole("textbox", { name: "Text content" }).fill("Day in the life");
  await page.getByRole("button", { name: "Add", exact: true }).click();
  if (await page.locator(".textOverlay").count() !== 1) throw new Error("Text overlay missing");
  await page.getByRole("button", { name: "Collapse text tools" }).click();
  await page.getByRole("button", { name: "More", exact: true }).click();
  const more = page.getByRole("dialog", { name: "More" });
  const squareRatio = more.getByRole("group", { name: "Video ratio" }).getByRole("button", { name: "1:1", exact: true });
  await squareRatio.click();
  if (await squareRatio.getAttribute("aria-pressed") !== "true") throw new Error("Square ratio was not selected in More");
  await more.getByRole("button", { name: "Close", exact: true }).click();
  await more.waitFor({ state: "hidden" });
  await page.waitForTimeout(350);
  if (await page.locator(".pvBox").evaluate(element => Math.abs(element.clientWidth - element.clientHeight)) > 2) throw new Error("Square ratio not applied");
  await page.keyboard.press("Control+z");
  await page.waitForTimeout(350);
  if (await page.locator(".pvBox").evaluate(element => Math.abs(element.clientWidth - element.clientHeight)) < 100) throw new Error("Ratio undo failed");
  await page.keyboard.press("Control+Shift+z");
  await page.waitForTimeout(350);
  if (await page.locator(".pvBox").evaluate(element => Math.abs(element.clientWidth - element.clientHeight)) > 2) throw new Error("Ratio redo failed");
  await page.getByRole("button", { name: "Next" }).click();
  const download = page.waitForEvent("download", { timeout: 30000 });
  await page.getByRole("button", { name: "Export video" }).click();
  const saved = await download.catch(async error => {
    throw new Error(`${error.message}\nExport UI: ${await page.getByRole('dialog').innerText()}\nNotifications: ${await page.locator('[data-notification-root]').allTextContents()}\nPage errors: ${errors.join('; ')}`);
  });
  if (!saved.suggestedFilename().startsWith("restyle-video.")) throw new Error("Unexpected export filename");
  if (process.argv[2]) {
    const real = await browser.newPage({ viewport: { width: 500, height: 1000 }, acceptDownloads: true });
    real.on("pageerror", error => errors.push(error.message));
    await real.goto(process.env.EDITOR_URL || process.env.RESTYLE_EDITOR_URL || "http://127.0.0.1:5173/", { waitUntil: "networkidle" });
    await real.locator('input[type="file"]').setInputFiles(process.argv[2]);
    await real.locator('.shutter[data-clips="1"] svg circle').waitFor();
    const chooser = real.waitForEvent("filechooser");
    await real.getByRole("button", { name: "Upload video" }).click();
    await (await chooser).setFiles(process.argv[2]);
    await real.locator('.shutter[data-clips="2"] svg circle').last().waitFor();
    await real.screenshot({ path: resolve(tmpdir(), "capture-gallery.png") });
    await real.getByRole("button", { name: "Undo last take" }).click();
    await real.locator('.shutter[data-clips="1"] svg circle').waitFor();
    await real.getByRole("button", { name: "Open editor" }).click();
    await real.locator(".pvVideo").waitFor();
    await real.waitForFunction(() => (document.querySelector(".pvVideo")?.videoWidth ?? 0) > 0);
    const original = await real.locator(".pvVideo").evaluate(video => ({ aspect: video.videoWidth / video.videoHeight, fit: getComputedStyle(video).objectFit }));
    const frameAspect = await real.locator(".pvBox").evaluate(box => box.clientWidth / box.clientHeight);
    if (original.fit !== "contain" || original.aspect <= 0 || frameAspect <= 0) throw new Error("Upload should retain its full uncropped frame");
    await real.locator(".tlClip").click();
    await real.getByRole("button", { name: "Replace" }).click();
    await real.locator('input[type="file"]').setInputFiles(process.argv[2]);
    await real.getByRole("heading", { name: "Edit" }).waitFor();
    if (await real.locator(".tlClip").count() !== 1) throw new Error("Replace should keep one clip");
    const beforeTrim = await real.locator(".tlClip").evaluate(element => element.getBoundingClientRect().width);
    const clipBox = await real.locator(".tlClip").boundingBox();
    if (!clipBox) throw new Error("Clip missing");
    const rowY = clipBox.y + clipBox.height / 2;
    for (let i = 0; i < 6; i += 1) {
      const reach = await real.locator(".handleR").boundingBox();
      if (reach && reach.x + reach.width < 480) break;
      await real.mouse.move(460, rowY);
      await real.mouse.down();
      await real.mouse.move(60, rowY, { steps: 8 });
      await real.mouse.up();
    }
    const handle = await real.locator(".handleR").boundingBox();
    if (!handle || handle.x + handle.width > 480) throw new Error("Trim handle missing");
    await real.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
    await real.mouse.down();
    await real.mouse.move(handle.x + handle.width / 2 - 10, handle.y + handle.height / 2, { steps: 5 });
    await real.mouse.up();
    const afterTrim = await real.locator(".tlClip").evaluate(element => element.getBoundingClientRect().width);
    if (afterTrim >= beforeTrim) throw new Error("Trim did not shorten the clip");
    await real.getByRole("button", { name: "Speed", exact: true }).click();
    await real.getByRole("button", { name: "2x" }).click();
    await real.getByRole("button", { name: "Close" }).click();
    await real.getByRole("button", { name: "Crop" }).click();
    await real.locator(".zoomRange").fill("135");
    await real.getByRole("button", { name: "Mirror" }).click();
    await real.getByRole("button", { name: "Close" }).click();
    await real.getByRole("button", { name: "Collapse clip tools" }).click();
    await real.getByRole("button", { name: "Sound" }).click();
    await real.getByRole("button", { name: /Summer Groove/ }).click();
    await real.getByRole("button", { name: "Close" }).click();
    await real.keyboard.press("Space");
    await real.waitForTimeout(450);
    await real.keyboard.press("Space");
    await real.keyboard.press("s");
    if (await real.locator(".tlClip").count() !== 2) throw new Error("Split did not create two clips");
    await real.getByRole("button", { name: "Next" }).click();
    const realDownload = real.waitForEvent("download", { timeout: 30000 });
    await real.getByRole("button", { name: "Export video" }).click();
    const realSaved = await realDownload;
    await realSaved.saveAs(resolve(tmpdir(), "capture-real-export.webm"));
    console.log("Real video upload, uncropped fit, replacement, trim, speed, crop, sound, split, and export passed");
    await real.close();
  }
  if (process.argv[3]) {
    const long = await browser.newPage();
    await long.goto(process.env.EDITOR_URL || process.env.RESTYLE_EDITOR_URL || "http://127.0.0.1:5173/", { waitUntil: "networkidle" });
    await long.locator('input[type="file"]').setInputFiles(process.argv[3]);
    await long.getByRole("button", { name: "Open editor" }).waitFor();
    const footer = await long.locator(".camFoot").innerText();
    const match = footer.match(/(\d+):(\d+)$/);
    if (!match || Number(match[1]) * 60 + Number(match[2]) <= 15) throw new Error(`Long upload was capped: ${footer}`);
    if (await long.locator('.shutter').getAttribute('data-scale') !== '60') throw new Error('Ring did not rescale from 10 to 60 seconds');
    await long.getByRole('button', { name: 'Open editor' }).click();
    await long.locator('.tlClip').click({ position: { x: 20, y: 20 } });
    await long.getByRole('button', { name: 'Speed', exact: true }).click();
    await long.getByRole('button', { name: '2x' }).click();
    await long.getByRole('button', { name: 'Close' }).click();
    await long.getByRole('button', { name: 'Back to camera' }).click();
    if (await long.locator('.shutter').getAttribute('data-scale') !== '10') throw new Error('Ring did not update after changing clip speed');
    console.log(`Unlimited upload passed: ${footer.replaceAll("\n", " ")}`);
    await long.close();
  }
  if (process.argv[4]) {
    const extended = await browser.newPage();
    await extended.goto(process.env.EDITOR_URL || process.env.RESTYLE_EDITOR_URL || "http://127.0.0.1:5173/", { waitUntil: 'networkidle' });
    await extended.locator('input[type="file"]').setInputFiles(process.argv[4]);
    await extended.locator('.shutter[data-scale="120"]').waitFor();
    const arc = Number((await extended.locator('.shutter svg circle').getAttribute('stroke-dasharray'))?.split(' ')[0]);
    if (arc <= 2 * Math.PI * 41 * .5 || arc >= 2 * Math.PI * 41) throw new Error('Extended ring fraction is wrong');
    await extended.close();
  }
  const cameraContext = await browser.newContext({ viewport: { width: 500, height: 1000 }, permissions: ["camera", "microphone"], acceptDownloads: true });
  const camera = await cameraContext.newPage();
  camera.on("pageerror", error => errors.push(error.message));
  await camera.goto(process.env.EDITOR_URL || process.env.RESTYLE_EDITOR_URL || "http://127.0.0.1:5173/", { waitUntil: "networkidle" });
  await camera.locator(".live").waitFor({ timeout: 10000 });
  await camera.waitForFunction(() => (document.querySelector(".live")?.videoWidth ?? 0) > 0);
  await camera.getByRole("button", { name: "Ratio" }).click();
  await camera.getByRole("menuitemradio", { name: "1:1" }).click();
  await camera.waitForFunction(() => {
    const frame = document.querySelector('.cameraFrame');
    return frame?.dataset.ratio === '1:1' && Math.abs(frame.clientWidth - frame.clientHeight) <= 2;
  });
  const cameraFrame = await camera.locator(".cameraFrame").evaluate(element => ({ width: element.clientWidth, height: element.clientHeight }));
  if (Math.abs(cameraFrame.width - cameraFrame.height) > 2) throw new Error(`Camera view does not show the selected ratio: ${JSON.stringify(cameraFrame)} ${await camera.locator('.cameraFrame').getAttribute('data-ratio')}`);
  await camera.getByRole("button", { name: "Record" }).click();
  await camera.waitForTimeout(700);
  await camera.getByRole("button", { name: "Stop recording" }).click();
  await camera.getByRole("button", { name: "Open editor" }).waitFor();
  await camera.getByRole("button", { name: "Open editor" }).click();
  await camera.locator(".pvVideo").waitFor();
  const recordedPreview = await camera.locator(".pvVideo").evaluate(video => ({ fit: getComputedStyle(video).objectFit, frame: { width: video.parentElement.clientWidth, height: video.parentElement.clientHeight } }));
  if (recordedPreview.fit !== "cover" || Math.abs(recordedPreview.frame.width - recordedPreview.frame.height) > 2) throw new Error("Recorded clip lost the camera ratio");
  await camera.locator(".tlClip").click();
  await camera.getByRole("button", { name: "Delete" }).click();
  await camera.getByRole("button", { name: "Record" }).waitFor();
  if (await camera.getByRole("heading", { name: "Edit" }).count()) throw new Error("Deleting the last clip did not return to camera");
  console.log("Permitted live camera and real MediaRecorder capture passed");
  await cameraContext.close();
  if (errors.length) throw new Error(errors.join("\n"));
  console.log(JSON.stringify({ clip: "recorded", editor: "opened", text: "added", ratio: "1:1", export: saved.suggestedFilename(), errors }, null, 2));
} finally {
  await browser.close();
}
