import type { PvoDiagnosticEvent, PvoDiagnosticSource } from "../../../../packages/pvo-sdk/index.js";

export type DebugResult = "done" | "failed" | "unavailable" | "no_action" | "blocked" | "held" | "waiting" | "running" | "ignored" | "cancelled" | "stopped";
export type DebugStageKind = "ok" | "fail" | "warn" | "ignored" | "wait" | "running" | "next";
export type DebugRecord = PvoDiagnosticEvent & {
  id: string;
  runId: string;
  sequence: number;
  elapsedMs: number;
  videoTime: number;
  sceneId: string;
  label?: string;
  target?: string;
  waitUntil?: number;
};
export type DebugComponent = {
  id: string;
  name: string;
  type: string;
  sceneId: string;
  sceneName: string;
  at: number;
  end: number;
  dispatch: "interaction" | "layer_end" | null;
  unanswered: "continue" | "pause" | null;
  hasAction: boolean;
  actionKnown: boolean;
  handled: boolean;
  dispatched: boolean;
  code: boolean;
  source: PvoDiagnosticSource;
  currentRevision: string;
  layer: number;
  layerCount: number;
  aboveVideo: boolean;
  ready: boolean;
  unavailable: boolean;
  failure?: string;
};
export type DebugPlayback = {
  clock: "unknown" | "media" | "timeline";
  sceneId: string;
  sceneName: string;
  videoTime: number;
  requested: "playing" | "paused";
  observed: "playing" | "paused" | "waiting" | "seeking" | "ended" | "error" | "unknown";
  holdingId: string | null;
  holdInteractionId: string | null;
  holdReason: string | null;
};
export type DebugRequestRow = {
  id: string;
  groupId: string;
  componentId?: string;
  componentName: string;
  method: string;
  url: string;
  host: string;
  path: string;
  videoTime: number;
  startedElapsedMs: number;
  durationMs?: number;
  status?: number;
  result: DebugResult;
  resultLabel: string;
  reason?: string;
  explanation: string;
  captured: boolean;
  requestBody?: unknown;
  responseBody?: unknown;
};
export type DebugRun = {
  id: string;
  projectId: string | null;
  build: string;
  startedAt: number;
  clockOriginMs: number;
  elapsedMs: number;
  endedAt?: number;
  status: "running" | "stopped" | "failed";
  records: DebugRecord[];
  components: DebugComponent[];
  currentState: Record<string, unknown>;
  playback: DebugPlayback;
  requests: DebugRequestRow[];
  pendingRequests: number;
  requestOverflow: number;
  componentOverflow: number;
  discarded: number;
};
export type DebugStage = {
  id: string;
  kind: DebugStageKind;
  videoTime: number;
  label: string;
  detail?: string;
  reason?: string;
};
export type DebugGroup = {
  id: string;
  kind: "interaction" | "component" | "playback" | "session";
  componentId?: string;
  componentName: string;
  target?: string;
  videoTime: number;
  result: DebugResult;
  resultLabel: string;
  summary: string;
  why: string;
  nextStep?: string;
  stages: DebugStage[];
  records: DebugRecord[];
  source?: PvoDiagnosticSource;
  waitUntil?: number;
  lastSequence: number;
};
export type DebugStatus = {
  state: "playing" | "paused" | "held" | "failed" | "waiting" | "stopped";
  title: string;
  sub?: string;
  holdComponentId?: string;
  sceneName: string;
  videoTime: number;
  requestsRunning: number;
  requestElapsed: number;
};
export type DebugStateRow = {
  path: string;
  value: unknown;
  displayValue: string;
  masked: boolean;
  changedAt?: number;
  before?: unknown;
};
export type DebugReadiness = DebugComponent & {
  status: "ready" | "active" | "ended" | "unavailable";
  interactive: boolean;
  interactiveLabel: string;
  lastInput?: { videoTime: number; target?: string };
};
