// Original npm nanoid 5.1.6 files; tarball integrity and MIT license retained below.
export default {
  name: "nanoid",
  version: "5.1.6",
  registryIntegrity:
    "sha512-c7+7RQ+dMB5dPwwCp4ee1/iV/q2P6aK1mTZcfr1BTuVlyW9hJYiMPybJCcnBlQtuSmTIWNeazm/zqNoZSSElBg==",
  files: [
    {
      path: "LICENSE",
      content:
        'The MIT License (MIT)\n\nCopyright 2017 Andrey Sitnik <andrey@sitnik.ru>\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the "Software"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n',
    },
    {
      path: "README.md",
      content:
        '# Nano ID\n\n<img src="https://ai.github.io/nanoid/logo.svg" align="right"\n     alt="Nano ID logo by Anton Lovchikov" width="180" height="94">\n\n**English** | [日本語](./README.ja.md) | [Русский](./README.ru.md) | [简体中文](./README.zh-CN.md) | [Bahasa Indonesia](./README.id-ID.md) | [한국어](./README.ko.md)\n\nA tiny, secure, URL-friendly, unique string ID generator for JavaScript.\n\n> “An amazing level of senseless perfectionism,\n> which is simply impossible not to respect.”\n\n* **Small.** 118 bytes (minified and brotlied). No dependencies.\n  [Size Limit] controls the size.\n* **Safe.** It uses hardware random generator. Can be used in clusters.\n* **Short IDs.** It uses a larger alphabet than UUID (`A-Za-z0-9_-`).\n  So ID size was reduced from 36 to 21 symbols.\n* **Portable.** Nano ID was ported\n  to over [20 programming languages](./README.md#other-programming-languages).\n\n```js\nimport { nanoid } from \'nanoid\'\nmodel.id = nanoid() //=> "V1StGXR8_Z5jdHi6B-myT"\n```\n\n---\n\n<img src="https://cdn.evilmartians.com/badges/logo-no-label.svg" alt="" width="22" height="16" />  Made at <b><a href="https://evilmartians.com/devtools?utm_source=nanoid&utm_campaign=devtools-button&utm_medium=github">Evil Martians</a></b>, product consulting for <b>developer tools</b>.\n\n---\n\n[online tool]: https://gitpod.io/#https://github.com/ai/nanoid/\n[with Babel]:  https://developer.epages.com/blog/coding/how-to-transpile-node-modules-with-babel-and-webpack-in-a-monorepo/\n[Size Limit]:  https://github.com/ai/size-limit\n\n\n## Docs\nRead full docs **[here](https://github.com/ai/nanoid#readme)**.\n',
    },
    {
      path: "bin/nanoid.js",
      content:
        "#!/usr/bin/env node\nimport { customAlphabet, nanoid } from '../index.js'\nfunction print(msg) {\n  process.stdout.write(msg + '\\n')\n}\nfunction error(msg) {\n  process.stderr.write(msg + '\\n')\n  process.exit(1)\n}\nif (process.argv.includes('--help') || process.argv.includes('-h')) {\n  print(`Usage\n  $ nanoid [options]\nOptions\n  -s, --size       Generated ID size\n  -a, --alphabet   Alphabet to use\n  -h, --help       Show this help\nExamples\n  $ nanoid -s 15\n  S9sBF77U6sDB8Yg\n  $ nanoid --size 10 --alphabet abc\n  bcabababca`)\n  process.exit()\n}\nlet alphabet, size\nfor (let i = 2; i < process.argv.length; i++) {\n  let arg = process.argv[i]\n  if (arg === '--size' || arg === '-s') {\n    size = Number(process.argv[i + 1])\n    i += 1\n    if (Number.isNaN(size) || size <= 0) {\n      error('Size must be positive integer')\n    }\n  } else if (arg === '--alphabet' || arg === '-a') {\n    alphabet = process.argv[i + 1]\n    i += 1\n  } else {\n    error('Unknown argument ' + arg)\n  }\n}\nif (alphabet) {\n  let customNanoid = customAlphabet(alphabet, size)\n  print(customNanoid())\n} else {\n  print(nanoid(size))\n}\n",
    },
    {
      path: "index.browser.js",
      content:
        "/* @ts-self-types=\"./index.d.ts\" */\nimport { urlAlphabet as scopedUrlAlphabet } from './url-alphabet/index.js'\nexport { urlAlphabet } from './url-alphabet/index.js'\nexport let random = bytes => crypto.getRandomValues(new Uint8Array(bytes))\nexport let customRandom = (alphabet, defaultSize, getRandom) => {\n  let mask = (2 << Math.log2(alphabet.length - 1)) - 1\n  let step = -~((1.6 * mask * defaultSize) / alphabet.length)\n  return (size = defaultSize) => {\n    let id = ''\n    while (true) {\n      let bytes = getRandom(step)\n      let j = step | 0\n      while (j--) {\n        id += alphabet[bytes[j] & mask] || ''\n        if (id.length >= size) return id\n      }\n    }\n  }\n}\nexport let customAlphabet = (alphabet, size = 21) =>\n  customRandom(alphabet, size | 0, random)\nexport let nanoid = (size = 21) => {\n  let id = ''\n  let bytes = crypto.getRandomValues(new Uint8Array((size |= 0)))\n  while (size--) {\n    id += scopedUrlAlphabet[bytes[size] & 63]\n  }\n  return id\n}\n",
    },
    {
      path: "index.d.ts",
      content:
        "/**\n * A tiny, secure, URL-friendly, unique string ID generator for JavaScript\n * with hardware random generator.\n *\n * ```js\n * import { nanoid } from 'nanoid'\n * model.id = nanoid() //=> \"V1StGXR8_Z5jdHi6B-myT\"\n * ```\n *\n * @module\n */\n\n/**\n * Generate secure URL-friendly unique ID.\n *\n * By default, the ID will have 21 symbols to have a collision probability\n * similar to UUID v4.\n *\n * ```js\n * import { nanoid } from 'nanoid'\n * model.id = nanoid() //=> \"Uakgb_J5m9g-0JDMbcJqL\"\n * ```\n *\n * @param size Size of the ID. The default size is 21.\n * @typeparam Type The ID type to replace `string` with some opaque type.\n * @returns A random string.\n */\nexport function nanoid<Type extends string>(size?: number): Type\n\n/**\n * Generate secure unique ID with custom alphabet.\n *\n * Alphabet must contain 256 symbols or less. Otherwise, the generator\n * will not be secure.\n *\n * @param alphabet Alphabet used to generate the ID.\n * @param defaultSize Size of the ID. The default size is 21.\n * @typeparam Type The ID type to replace `string` with some opaque type.\n * @returns A random string generator.\n *\n * ```js\n * const { customAlphabet } = require('nanoid')\n * const nanoid = customAlphabet('0123456789абвгдеё', 5)\n * nanoid() //=> \"8ё56а\"\n * ```\n */\nexport function customAlphabet<Type extends string>(\n  alphabet: string,\n  defaultSize?: number\n): (size?: number) => Type\n\n/**\n * Generate unique ID with custom random generator and alphabet.\n *\n * Alphabet must contain 256 symbols or less. Otherwise, the generator\n * will not be secure.\n *\n * ```js\n * import { customRandom } from 'nanoid/format'\n *\n * const nanoid = customRandom('abcdef', 5, size => {\n *   const random = []\n *   for (let i = 0; i < size; i++) {\n *     random.push(randomByte())\n *   }\n *   return random\n * })\n *\n * nanoid() //=> \"fbaef\"\n * ```\n *\n * @param alphabet Alphabet used to generate a random string.\n * @param size Size of the random string.\n * @param random A random bytes generator.\n * @typeparam Type The ID type to replace `string` with some opaque type.\n * @returns A random string generator.\n */\nexport function customRandom<Type extends string>(\n  alphabet: string,\n  size: number,\n  random: (bytes: number) => Uint8Array\n): () => Type\n\n/**\n * URL safe symbols.\n *\n * ```js\n * import { urlAlphabet } from 'nanoid'\n * const nanoid = customAlphabet(urlAlphabet, 10)\n * nanoid() //=> \"Uakgb_J5m9\"\n * ```\n */\nexport const urlAlphabet: string\n\n/**\n * Generate an array of random bytes collected from hardware noise.\n *\n * ```js\n * import { customRandom, random } from 'nanoid'\n * const nanoid = customRandom(\"abcdef\", 5, random)\n * ```\n *\n * @param bytes Size of the array.\n * @returns An array of random bytes.\n */\nexport function random(bytes: number): Uint8Array\n",
    },
    {
      path: "index.js",
      content:
        "import { webcrypto as crypto } from 'node:crypto'\nimport { urlAlphabet as scopedUrlAlphabet } from './url-alphabet/index.js'\nexport { urlAlphabet } from './url-alphabet/index.js'\nconst POOL_SIZE_MULTIPLIER = 128\nlet pool, poolOffset\nfunction fillPool(bytes) {\n  if (!pool || pool.length < bytes) {\n    pool = Buffer.allocUnsafe(bytes * POOL_SIZE_MULTIPLIER)\n    crypto.getRandomValues(pool)\n    poolOffset = 0\n  } else if (poolOffset + bytes > pool.length) {\n    crypto.getRandomValues(pool)\n    poolOffset = 0\n  }\n  poolOffset += bytes\n}\nexport function random(bytes) {\n  fillPool((bytes |= 0))\n  return pool.subarray(poolOffset - bytes, poolOffset)\n}\nexport function customRandom(alphabet, defaultSize, getRandom) {\n  let mask = (2 << (31 - Math.clz32((alphabet.length - 1) | 1))) - 1\n  let step = Math.ceil((1.6 * mask * defaultSize) / alphabet.length)\n  return (size = defaultSize) => {\n    if (!size) return ''\n    let id = ''\n    while (true) {\n      let bytes = getRandom(step)\n      let i = step\n      while (i--) {\n        id += alphabet[bytes[i] & mask] || ''\n        if (id.length >= size) return id\n      }\n    }\n  }\n}\nexport function customAlphabet(alphabet, size = 21) {\n  return customRandom(alphabet, size, random)\n}\nexport function nanoid(size = 21) {\n  fillPool((size |= 0))\n  let id = ''\n  for (let i = poolOffset - size; i < poolOffset; i++) {\n    id += scopedUrlAlphabet[pool[i] & 63]\n  }\n  return id\n}\n",
    },
    {
      path: "nanoid.js",
      content:
        'let a="useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict";export let nanoid=(e=21)=>{let t="",r=crypto.getRandomValues(new Uint8Array(e));for(let n=0;n<e;n++)t+=a[63&r[n]];return t};',
    },
    {
      path: "non-secure/index.d.ts",
      content:
        "/**\n * By default, Nano ID uses hardware random bytes generation for security\n * and low collision probability. If you are not so concerned with security,\n * you can use it for environments without hardware random generators.\n *\n * ```js\n * import { nanoid } from 'nanoid/non-secure'\n * const id = nanoid() //=> \"Uakgb_J5m9g-0JDMbcJqLJ\"\n * ```\n *\n * @module\n */\n\n/**\n * Generate URL-friendly unique ID. This method uses the non-secure\n * predictable random generator with bigger collision probability.\n *\n * ```js\n * import { nanoid } from 'nanoid/non-secure'\n * model.id = nanoid() //=> \"Uakgb_J5m9g-0JDMbcJqL\"\n * ```\n *\n * @param size Size of the ID. The default size is 21.\n * @typeparam Type The ID type to replace `string` with some opaque type.\n * @returns A random string.\n */\nexport function nanoid<Type extends string>(size?: number): Type\n\n/**\n * Generate a unique ID based on a custom alphabet.\n * This method uses the non-secure predictable random generator\n * with bigger collision probability.\n *\n * @param alphabet Alphabet used to generate the ID.\n * @param defaultSize Size of the ID. The default size is 21.\n * @typeparam Type The ID type to replace `string` with some opaque type.\n * @returns A random string generator.\n *\n * ```js\n * import { customAlphabet } from 'nanoid/non-secure'\n * const nanoid = customAlphabet('0123456789абвгдеё', 5)\n * model.id = nanoid() //=> \"8ё56а\"\n * ```\n */\nexport function customAlphabet<Type extends string>(\n  alphabet: string,\n  defaultSize?: number\n): (size?: number) => Type\n",
    },
    {
      path: "non-secure/index.js",
      content:
        "/* @ts-self-types=\"./index.d.ts\" */\nlet urlAlphabet =\n  'useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict'\nexport let customAlphabet = (alphabet, defaultSize = 21) => {\n  return (size = defaultSize) => {\n    let id = ''\n    let i = size | 0\n    while (i--) {\n      id += alphabet[(Math.random() * alphabet.length) | 0]\n    }\n    return id\n  }\n}\nexport let nanoid = (size = 21) => {\n  let id = ''\n  let i = size | 0\n  while (i--) {\n    id += urlAlphabet[(Math.random() * 64) | 0]\n  }\n  return id\n}\n",
    },
    {
      path: "package.json",
      content:
        '{\n  "name": "nanoid",\n  "version": "5.1.6",\n  "description": "A tiny (118 bytes), secure URL-friendly unique string ID generator",\n  "keywords": [\n    "uuid",\n    "random",\n    "id",\n    "url"\n  ],\n  "type": "module",\n  "engines": {\n    "node": "^18 || >=20"\n  },\n  "funding": [\n    {\n      "type": "github",\n      "url": "https://github.com/sponsors/ai"\n    }\n  ],\n  "author": "Andrey Sitnik <andrey@sitnik.ru>",\n  "license": "MIT",\n  "repository": "ai/nanoid",\n  "exports": {\n    ".": {\n      "types": "./index.d.ts",\n      "browser": "./index.browser.js",\n      "react-native": "./index.browser.js",\n      "default": "./index.js"\n    },\n    "./non-secure": "./non-secure/index.js",\n    "./package.json": "./package.json"\n  },\n  "browser": {\n    "./index.js": "./index.browser.js"\n  },\n  "react-native": {\n    "./index.js": "./index.browser.js"\n  },\n  "bin": "./bin/nanoid.js",\n  "sideEffects": false,\n  "types": "./index.d.ts"\n}\n',
    },
    {
      path: "url-alphabet/index.js",
      content:
        "export const urlAlphabet =\n  'useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict'\n",
    },
  ],
};
