import { chromium } from "playwright-core";
import { resolve } from "node:path";
import { tmpdir } from "node:os";

const browser = await chromium.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true, args: ["--no-sandbox", "--use-fake-device-for-media-stream"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 1050 }, acceptDownloads: true });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
try {
  await page.goto("http://127.0.0.1:5173/", { waitUntil: "networkidle" });
  await page.getByRole("button", { name: "Record" }).waitFor();
  await page.screenshot({ path: resolve(tmpdir(), "capture-camera.png") });
  await page.getByRole("button", { name: "Record" }).click();
  await page.waitForTimeout(900);
  await page.getByRole("button", { name: "Stop recording" }).click();
  await page.getByRole("button", { name: "Open editor" }).waitFor();
  await page.getByRole("button", { name: "Open editor" }).click();
  await page.getByRole("heading", { name: "Edit" }).waitFor();
  await page.screenshot({ path: resolve(tmpdir(), "capture-editor.png") });
  await page.locator(".tlClip").click();
  await page.getByRole("button", { name: "Collapse clip tools" }).waitFor();
  await page.getByRole("button", { name: "Collapse clip tools" }).click();
  await page.getByRole("button", { name: "Text", exact: true }).click();
  await page.getByPlaceholder("Type something…").fill("Day in the life");
  await page.getByRole("button", { name: "Add", exact: true }).click();
  if (await page.locator(".textOverlay").count() !== 1) throw new Error("Text overlay missing");
  await page.getByRole("button", { name: "Ratio", exact: true }).click();
  await page.getByRole("button", { name: "1:1" }).click();
  await page.getByRole("button", { name: "Close" }).click();
  await page.waitForTimeout(350);
  if (await page.locator(".pvBox").evaluate(element => Math.abs(element.clientWidth - element.clientHeight)) > 2) throw new Error("Square ratio not applied");
  await page.keyboard.press("Control+z");
  await page.waitForTimeout(350);
  if (await page.locator(".pvBox").evaluate(element => Math.abs(element.clientWidth - element.clientHeight)) < 100) throw new Error("Ratio undo failed");
  await page.keyboard.press("Control+Shift+z");
  await page.waitForTimeout(350);
  if (await page.locator(".pvBox").evaluate(element => Math.abs(element.clientWidth - element.clientHeight)) > 2) throw new Error("Ratio redo failed");
  await page.getByRole("button", { name: "Next" }).click();
  const download = page.waitForEvent("download", { timeout: 30000 });
  await page.getByRole("button", { name: "Export video" }).click();
  const saved = await download;
  if (!saved.suggestedFilename().startsWith("restyle-video.")) throw new Error("Unexpected export filename");
  if (process.argv[2]) {
    const real = await browser.newPage({ viewport: { width: 500, height: 1000 }, acceptDownloads: true });
    real.on("pageerror", error => errors.push(error.message));
    await real.goto("http://127.0.0.1:5173/", { waitUntil: "networkidle" });
    await real.locator('input[type="file"]').setInputFiles(process.argv[2]);
    await real.getByRole("button", { name: "Open editor" }).click();
    await real.locator(".pvVideo").waitFor();
    await real.locator(".tlClip").click();
    await real.getByRole("button", { name: "Replace" }).click();
    await real.locator('input[type="file"]').setInputFiles(process.argv[2]);
    await real.getByRole("heading", { name: "Edit" }).waitFor();
    if (await real.locator(".tlClip").count() !== 1) throw new Error("Replace should keep one clip");
    const beforeTrim = await real.locator(".tlClip").evaluate(element => element.getBoundingClientRect().width);
    const handle = await real.locator(".handleR").boundingBox();
    if (!handle) throw new Error("Trim handle missing");
    await real.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
    await real.mouse.down();
    await real.mouse.move(handle.x + handle.width / 2 - 10, handle.y + handle.height / 2, { steps: 5 });
    await real.mouse.up();
    const afterTrim = await real.locator(".tlClip").evaluate(element => element.getBoundingClientRect().width);
    if (afterTrim >= beforeTrim) throw new Error("Trim did not shorten the clip");
    await real.getByRole("button", { name: "Speed", exact: true }).click();
    await real.getByRole("button", { name: "2x" }).click();
    await real.getByRole("button", { name: "Close" }).click();
    await real.getByRole("button", { name: "Crop" }).click();
    await real.locator(".zoomRange").fill("135");
    await real.getByRole("button", { name: "Mirror" }).click();
    await real.getByRole("button", { name: "Close" }).click();
    await real.getByRole("button", { name: "Filter", exact: true }).click();
    await real.getByRole("button", { name: "Warm" }).click();
    await real.getByRole("button", { name: "Close" }).click();
    await real.getByRole("button", { name: "Collapse clip tools" }).click();
    await real.getByRole("button", { name: "Sound" }).click();
    await real.getByRole("button", { name: /Summer Groove/ }).click();
    await real.getByRole("button", { name: "Close" }).click();
    await real.keyboard.press("Space");
    await real.waitForTimeout(450);
    await real.keyboard.press("Space");
    await real.keyboard.press("s");
    if (await real.locator(".tlClip").count() !== 2) throw new Error("Split did not create two clips");
    await real.getByRole("button", { name: "Next" }).click();
    const realDownload = real.waitForEvent("download", { timeout: 30000 });
    await real.getByRole("button", { name: "Export video" }).click();
    const realSaved = await realDownload;
    await realSaved.saveAs(resolve(tmpdir(), "capture-real-export.webm"));
    console.log("Real video upload, replacement, trim, speed, crop, filter, sound, split, and export passed");
    await real.close();
  }
  const cameraContext = await browser.newContext({ viewport: { width: 500, height: 1000 }, permissions: ["camera", "microphone"] });
  const camera = await cameraContext.newPage();
  camera.on("pageerror", error => errors.push(error.message));
  await camera.goto("http://127.0.0.1:5173/", { waitUntil: "networkidle" });
  await camera.locator(".live").waitFor({ timeout: 10000 });
  await camera.waitForFunction(() => (document.querySelector(".live")?.videoWidth ?? 0) > 0);
  await camera.getByRole("button", { name: "Record" }).click();
  await camera.waitForTimeout(700);
  await camera.getByRole("button", { name: "Stop recording" }).click();
  await camera.getByRole("button", { name: "Open editor" }).waitFor();
  await camera.getByRole("button", { name: "Open editor" }).click();
  await camera.locator(".pvVideo").waitFor();
  await camera.locator(".tlClip").click();
  await camera.getByRole("button", { name: "Delete" }).click();
  await camera.getByRole("button", { name: "Record" }).waitFor();
  if (await camera.getByRole("heading", { name: "Edit" }).count()) throw new Error("Deleting the last clip did not return to camera");
  console.log("Permitted live camera and real MediaRecorder capture passed");
  await cameraContext.close();
  if (errors.length) throw new Error(errors.join("\n"));
  console.log(JSON.stringify({ clip: "recorded", editor: "opened", text: "added", ratio: "1:1", export: saved.suggestedFilename(), errors }, null, 2));
} finally {
  await browser.close();
}
