import assert from "node:assert/strict";
import path from "node:path";

const snapshot = page => page.evaluate(async () => {
  const { useCapture } = await import("/src/state/captureStore.ts");
  const { projectSnapshot } = await import("/src/state/project/history.ts");
  const state = useCapture.getState();
  const video = document.querySelector(".pvVideo");
  return {
    project: JSON.parse(JSON.stringify(projectSnapshot(state))), past: state.past.length, t: state.t, playing: state.playing,
    holdingId: state.tryMode?.holdingId ?? null,
    capturedResponses: state.tryMode?.capturedResponses ?? {}, dispatched: state.tryMode?.dispatched ?? [],
    video: video ? { time: video.currentTime, paused: video.paused, seeking: video.seeking } : null,
    rawPauseEvents: window.__acceptancePlayback?.pauseEvents ?? [],
  };
});

/** Exercise actual rendered choices generated by the model, with no project corrections. */
export async function verifyRealQuizPlayback({ page, steps, directory, record }) {
  const completed = steps.at(-1);
  const quiz = completed.after.scenes.find(scene => scene.id === "main").components.find(component => component.type === "choice");
  assert(quiz, "The real model must produce an authored quiz before viewer verification");
  const fields = completed.components[quiz.id].fields;
  const labels = fields.options.map(option => option.label);
  assert.equal(labels.length, 2);
  const boundary = quiz.at + quiz.dur;
  assert.equal(boundary, 2, "The semantic fixture requires the quiz to hold at two seconds");
  const authored = await snapshot(page);
  assert.deepEqual(authored.project, completed.after, "Viewer test must use the exact real model result");
  await page.evaluate(async () => {
    const { useCapture } = await import("/src/state/captureStore.ts");
    const originalPause = HTMLMediaElement.prototype.pause;
    window.__acceptancePlayback = { originalPause, pauseEvents: [], store: useCapture };
    HTMLMediaElement.prototype.pause = function (...args) {
      if (this.matches(".pvVideo") && !this.paused && useCapture.getState().tryMode?.holdingId) {
        window.__acceptancePlayback.pauseEvents.push({ time: this.currentTime, at: performance.now() });
      }
      return originalPause.apply(this, args);
    };
  });
  const component = page.locator(`[data-preview-component="${quiz.id}"]`);
  const controls = quiz.code?.custom ? component.frameLocator(`iframe[title="Component ${quiz.id}"]`) : component;
  const button = index => controls.getByRole("button", { name: labels[index], exact: true });
  const stop = async () => {
    await page.getByRole("button", { name: "Stop trying", exact: true }).click();
    await page.getByRole("button", { name: "Try", exact: true }).waitFor();
    const state = await snapshot(page);
    assert.deepEqual(state.project, authored.project, "Viewer actions cannot mutate authored content");
    assert.equal(state.past, authored.past, "Viewer answers cannot add editing history");
    assert.equal(state.t, authored.t, "Stop trying restores the editing playhead");
  };
  const start = () => page.getByRole("button", { name: "Try", exact: true }).click();
  const resume = () => page.waitForFunction(({ id, boundary }) => {
    const state = window.__acceptancePlayback.store.getState(), video = document.querySelector(".pvVideo");
    return state.tryMode?.dispatched.includes(id) && state.tryMode.holdingId === null
      && state.playing && video && !video.paused && video.currentTime > boundary + 0.3;
  }, { id: quiz.id, boundary }, { timeout: 10000 });
  try {
    for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) {
      await page.setViewportSize(viewport);
      for (let index = 0; index < labels.length; index += 1) {
        const pauseCount = (await snapshot(page)).rawPauseEvents.length;
        await start();
        await page.waitForFunction(({ id, boundary }) => {
          const state = window.__acceptancePlayback.store.getState(), video = document.querySelector(".pvVideo");
          return state.tryMode?.holdingId === id && !state.playing && Math.abs(state.t - boundary) < 0.001
            && video?.paused && !video.seeking && Math.abs(video.currentTime - boundary) < 0.02;
        }, { id: quiz.id, boundary }, { timeout: 10000 });
        await controls.getByText(fields.prompt, { exact: true }).waitFor();
        const visibleButtons = await controls.getByRole("button").allTextContents();
        assert.deepEqual(visibleButtons.map(label => label.trim()), labels);
        const held = await snapshot(page);
        record({ phase: "held", viewport, answer: labels[index], visibleButtons, state: held });
        assert.equal(held.holdingId, quiz.id, "The observed state must actually be holding this quiz");
        assert.equal(held.playing, false); assert.equal(held.video.paused, true);
        assert.equal(held.video.seeking, false);
        assert(Math.abs(held.t - boundary) < 0.001, "The observed editor clock must equal the authored boundary");
        assert(Math.abs(held.video.time - boundary) < 0.02, "The observed media clock must equal the authored boundary");
        assert(held.rawPauseEvents.length > pauseCount, "Actual video.pause must stop the running media");
        assert(held.rawPauseEvents.at(-1).time < boundary + 0.051,
          `Media crossed the hold boundary before pausing (${held.rawPauseEvents.at(-1).time}s)`);
        await page.waitForTimeout(600);
        const stillHeld = await snapshot(page);
        record({ phase: "still-held", viewport, answer: labels[index], state: stillHeld });
        assert.equal(stillHeld.holdingId, quiz.id); assert.equal(stillHeld.playing, false);
        assert.equal(stillHeld.video.paused, true);
        assert(Math.abs(stillHeld.video.time - held.video.time) < 0.005, "Unanswered media must remain stationary");
        await page.screenshot({ path: path.join(directory, `quiz-hold-${viewport.width}-${index}.png`) });
        await button(index).click();
        await resume();
        record({ phase: "resumed", viewport, answer: labels[index], state: await snapshot(page) });
        await stop();
      }
      if (quiz.responsePolicy.dispatch === "layer_end") {
        await start();
        await button(0).click();
        await page.waitForFunction(id => {
          return Boolean(window.__acceptancePlayback.store.getState().tryMode?.capturedResponses[id]);
        }, quiz.id, { timeout: 1000 });
        const early = await snapshot(page);
        record({ phase: "early-answer", viewport, answer: labels[0], state: early });
        assert(early.t < boundary, "Early answer must be captured before the authored boundary");
        assert(!early.dispatched.includes(quiz.id), "Layer-end policy must wait before dispatching the early answer");
        assert.equal(early.holdingId, null); assert.equal(early.playing, true);
        await resume();
        record({ phase: "early-answer-dispatched", viewport, answer: labels[0], state: await snapshot(page) });
        await stop();
      }
    }
  } finally {
    await page.evaluate(() => {
      if (window.__acceptancePlayback) HTMLMediaElement.prototype.pause = window.__acceptancePlayback.originalPause;
    });
  }
}
