export type LookPreset = "bold" | "soft" | "minimal" | "contrast";
export type ComponentScale = { scale?: number; scaleX?: number; scaleY?: number };
export type ComponentGeometry = ComponentScale & { width?: number; height?: number };
export type ComponentDimensions = { width: number; height: number };
export const MAX_COMPONENT_PIXELS: number;
export function canvasPixelSize(width: number, height: number): ComponentDimensions;
export function componentPixelDimension(value: unknown): number | undefined;
export function componentPixelSize(component: ComponentGeometry | null | undefined, natural: ComponentDimensions): ComponentDimensions;
export function componentPixelTransform(component: ComponentGeometry, natural?: ComponentDimensions | null): ComponentDimensions;
export function observeComponentSize(element: HTMLElement, onSize: (size: ComponentDimensions) => void): () => void;
export const MIN_COMPONENT_SCALE: number;
export const MAX_COMPONENT_SCALE: number;
export function componentScale(value: unknown): number;
export function componentSize(component?: ComponentScale | null): { width: number; height: number };
export type LookSize = "S" | "M" | "L" | "XL";
export type LookAlign = "left" | "center" | "right";
export type LookRadius = 0 | 6 | 14 | 22 | 999;
export type LookWeight = 600 | 700 | 800;
export type ButtonLook = { fill: string; text: string; border: string; size: LookSize; weight: LookWeight; radius: LookRadius };
export type ComponentLook = {
  preset: LookPreset | "custom";
  basePreset: LookPreset;
  whole: { bg: string; border: string; text: string; radius: LookRadius; align: LookAlign };
  heading: { color: string; size: LookSize; align: LookAlign };
  body: { color: string; size: LookSize; weight: LookWeight; align: LookAlign };
  btns: ButtonLook[];
};
export const LOOK_PRESETS: LookPreset[];
export const LOOK_NAMES: Record<LookPreset | "custom", string>;
export const LOOK_PALETTE: string[];
export const LOOK_SIZES: Record<"heading" | "body" | "button" | "height", Record<LookSize, number>>;
export function createLook(preset?: LookPreset, buttonCount?: number): ComponentLook;
export function cloneLook(look: ComponentLook): ComponentLook;
export function normalizeLook(look: unknown, buttonCount?: number): ComponentLook;
export function normalizeHex(value: string): string | null;
export function lookStyles(look: unknown, unit?: number, buttonCount?: number): { whole: Record<string, string | number>; heading: Record<string, string | number>; body: Record<string, string | number>; buttons: Record<string, string | number>[]; field: Record<string, string | number> };
