export function animationInstructions(available) {
  if (!available) return "\nLayer keyframe animation is not available in this editor session. Do not invent animation operations.";
  return `
Layer keyframes are available for video clips, text, components, independent audio and scene music. Use these native operations:
- animation.set {sceneId,target,tracks} replaces ONLY the supplied property curves; all unmentioned curves remain. target is {kind:"clip"|"text"|"audio",id:number}, {kind:"component",id:string}, or {kind:"music"}. Each property curve is an ordered array of {time,value,easing}. Every operation time is a SCENE TIMELINE second inside the selected layer's visible/audible range. Do not use source times in operations.
- animation.remove {sceneId,target,property,time} removes one keyframe at that scene time.
- animation.clear {sceneId,target,property?} removes the requested property curve, or all this layer's curves when property is omitted.
Visual properties are x/y OFFSETS in canvas percentage points from the layer's static placement, scaleX/scaleY MULTIPLIERS of static size, rotation additional degrees around the center, opacity a MULTIPLIER of static opacity. x/y range -1000..1000, scaleX/Y 0..10, rotation -36000..36000, opacity 0..1. Clip visual offsets move the frame from its existing center. Audio and music support gain ONLY, 0..1 times the authored volume. Video clips also support gain. No sound is created by a music animation.
Default animation values are x=0,y=0,scaleX=1,scaleY=1,rotation=0,opacity=1,gain=1. A track holds its first value before the first keyframe and its last value after the last, so a fade requires explicit endpoint keys; a single keyframe changes the whole visible layer. Include unchanged endpoint values when the rest of the layer must be preserved. Easing belongs to the outgoing key: linear, hold (no interpolation until the next key), ease-in, ease-out or ease-in-out. Use a few meaningful keys for authored motion. To change an existing curve preserve the keys that should remain in the supplied replacement. Do not erase other authored movement accidentally.
Project context animation.tracks uses canonical storage clocks: video/audio keyframe times are ORIGINAL SOURCE seconds, so sceneTime=start+(key.time-sourceIn)/speed; text key times are relative to text.start; component key times are relative to component.at; musicAnimation key times are scene seconds. Convert existing keys to scene times before returning animation.set/remove. This preserves media motion through trims, speed edits and splits, and overlay motion when a layer moves.
For example, to fade a text layer in from scene seconds 2 to 3 and leave it fully visible afterward, use opacity:[{time:2,value:0,easing:"linear"},{time:3,value:1,easing:"linear"}] on its existing target ID. Create a missing text/component first, wait for its real ID, then animate it. Manual and AI keyframes share the same editable timeline and Undo. Keyframes do not infer object tracks: do not claim to follow an unseen car or hand unless actual tracking evidence is available. Sampled frame descriptions alone are not a verified continuous track.
`;
}
