export function trackingInstructions(available) {
  if (!available) return "\nObject tracking is unavailable in this session. Do not invent object_tracking or animation.follow tools, and do not fabricate paths from sparse frame descriptions.";
  return `
Use ordinary animation operations directly for authored fades, slides, scaling, rotation and volume changes. Use object_tracking when the requested motion must follow an actual subject in video or keep that subject centered. Request frame inspection first only when needed to identify the source, object or interval; a clear text description and known clip range can go directly to tracking. Tracking does not locate spoken words or determine a story's punchline; use transcript/word timing for speech and frame evidence for visual meaning.
SAM 3.1 object tracking is available. Request {kind:"object_tracking",sceneId,clipId,start,end,target:{kind:"text",text:"the red car"}} or target:{kind:"point",x:0.5,y:0.6}. A point uses normalized canvas coordinates (0..1) on the FIRST requested frame; use a point only when the creator supplied it or actual frame evidence identifies it. Track at most ten scene seconds inside one video clip. Frames are video-only, rendered with the clip's actual fit/mirror/zoom/current animation at 15fps, at most 640px long edge. Text/component overlays are not tracked. Sampling may miss fast events or brief occlusion; do not call it continuous ground truth.
The tool returns an actual observation ID, scene/clip/window, frameCount and timestamped measured boxes from SAM 3.1. x/y are BOX CENTERS normalized to the inspected canvas; width/height are normalized box dimensions. visible=false or score<0.25 is missing evidence, never a reliable position. At least two confident visible samples are required before following; one detected frame alone is not a track. Text prompts can be ambiguous; identify one object or use a creator-selected point instead of silently following several objects.
After a successful observation, use {kind:"animation.follow",sceneId,target,observationId,anchor:"center"|"top",offsetX,offsetY}. target may be an existing text/component, or the SAME video clip that was tracked. Offsets use percentage points of canvas width/height (-100..100). The target must span the complete observed interval. The browser derives editable x/y curves from the registered actual evidence, so do not fabricate point arrays or copy an old conversation ID. Other property animations are preserved.
Text/components retain their initial separation from the tracked center or top of the box, then add the requested offset. Use zero offsets to follow without jumping the layer onto the subject. Lost observations hold the last position and hide the overlay until evidence returns. Existing opacity curves that conflict with loss visibility require a shorter continuously visible section or explicit clearing; do not erase a user's opacity animation without permission in their task. Tracking a video clip instead creates a camera-follow/reframe: it offsets the original clip so the measured subject stays at canvas center plus the requested offset. Camera tracking holds through missing observations and never blacks out the footage. A different sequential clip cannot use that source's tracking evidence.
Generated position keys use one-second intervals, both endpoints and additional measured loss/reappearance boundaries, with no interpolation across missing intervals. These are readable editable keys, not a claim of frame-perfect motion; verify the prepared motion and use a shorter interval when necessary. The creator can re-fit half-, one- or two-second density from saved measurements without another tracking request. At most 120 keys per resulting curve are permitted; overly complex paths are rejected rather than truncated. Tracking over part of an existing eased position curve may require tracking its whole span. Reinspect if source footage, clip timing, geometry or canvas ratio changes; adding or editing an unrelated overlay alone does not invalidate measured video boxes. Camera-follow changes the inspected source motion, so a later follow cannot reuse that observation even within the same reply. Prepare attachments from the original evidence before camera-follow, or inspect the reframed footage again.
`;
}
